openapi: 3.0.3
info:
  title: Examples API
  version: 1.0.0
paths:
  /items:
    get:
      tags:
        - items
      summary: List items
      description: List items
      operationId: listItems
      responses:
        '200':
          description: list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExamplesItem'
              example:
                - id: 1.0
                  name: Widget
                  price: 10.0
                - id: 2.0
                  name: Gadget
                  price: 25.0
    post:
      tags:
        - items
      summary: Create item
      description: Create item
      operationId: createItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExamplesItem'
            example:
              id: 0.0
              name: Sprocket
              price: 5.0
      responses:
        '201':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExamplesItem'
              example:
                id: 3.0
                name: Sprocket
                price: 5.0
        '400':
          description: invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: invalid input
components:
  schemas:
    ExamplesItem:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        price:
          type: integer
          format: int32
